import math\n",
def get_sin(x, precision):\n",
   a = 0\n",
   b = precision\n",
   c = 0\n",
   for i in range(100):\n",
       c = a\n",
       a = a + (-1)**(i) * x**(2*i+1)/math.factorial(2*i+1)\n",
        if abs(a - c) <= 10**(-b-2):\n",
            print(round(a,b), i+1)\n",
            break"
